### ISSUE TITLE
Path must be absolute ("/tmp/") - Windows machine

### ISSUE THREAD

**Issue by Soufraz** [NitMedia/wkhtml2pdf#33]
Hi folks,
On windows run a xampp server, when I try generate a pdf with wkhtmltopdf, I get this error:

Path must be absolute ("/tmp/")

How to fixed this specifically on windows?
I need set my windows path tmp? I did try it, buth nothing yet..
Thanks advance..

**Comment by cristinadd** [comment]
Hi,
I am on windows and run a xampp server too, I tried all things above, downloaded the windows binary creating the config file, set $read_error = false but I get ["stderr"]=> string(101) "'C:\Program' is not recognized as an internal or external command, operable program or batch file. "

**Comment by parhs** [comment]
@cristinadd I said read_output  for false check the link. However clonthu might have added it

**Comment by cristinadd** [comment]
@parhs I set and $read_output = false but nothing happens.

**Comment by bretto36** [comment]
@cristinadd Can you install the files in c: instead of in Program files folder as the shell commands don't like spaces. You normally have to use the special naming for Program~% or something like that. It was easier to uninstall the files, then reinstall in a base folder. C:/wkhtml2pdf/

**Comment by nahuelhds** [comment]
In my case, I'm on windows 64 bits, and the problem was because the wkhtmltopdf-i386 is 32bits, so I needed to include the 64 bits binary. Plus, I've renamed the file with ".exe" to make it work.
