### ISSUE TITLE
ubuntu 14.04 Unable to load library icui18n

### ISSUE THREAD

**Issue by nirradian** [NitMedia/wkhtml2pdf#41]
I'm getting this error when trying to save an html to a file 

System error <pre>Unable to load library icui18n "Cannot load library icui18n: (icui18n: cannot open shared object file: No such file or directory)

It seems to be some compatibility problem, have you seen this before?

**Comment by chonthu** [comment]
Yes, this is a debian issue with minimal install, your missing libraries needed for wkhtmltopdf lib to work


Best

-- 






Nithin Meppurathu

**Comment by nirradian** [comment]
Hi Thanks for the quick reply!

Its an ubuntu 14.04, it fails to find libicu52 i believe (I have a different 13.10 ubuntu that runs fine with libicu48) but this one simply doesn't work.

this is the full error:
exception 'Exception' with message 'System error <pre>Unable to load library icui18n "Cannot load library icui18n: (icui18n: cannot open shared object file: No such file or directory)"
Loading pages (1/6)
Warning: SSL error ignored
Warning: SSL error ignored
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
</pre>' in /web/gene-cloud/vendor/nitmedia/wkhtml2pdf/src/Nitmedia/Wkhtml2pdf/Wkhtml2pdf.php:884

**Comment by chonthu** [comment]
Right yeah you missing the package on your Debian based system.


Have you tried




apt-get install libicu48


Best

-- 






Nithin Meppurathu

**Comment by nirradian** [comment]
we installed from deb: libicu48_4.8.1.1-12ubuntu2_amd64.deb, the error has changed to something a bit more cryptic 

Exception: System error <pre>Loading pages (1/6)
Warning: SSL error ignored                                        
Warning: SSL error ignored
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done                                                                      
</pre>

**Comment by nirradian** [comment]
So i went into the code /web/gene-cloud/vendor/nitmedia/wkhtml2pdf/src/Nitmedia/Wkhtml2pdf/Wkhtml2pdf.php line 884 and remarked that exception clause and I get my pdf and it looks just fine. 

I'll have to live with this solution for now..... I think the fact that there is no longer an error string there might point to some kind of bug in that if clause. what do you think?

**Comment by chonthu** [comment]
Seems like the ssl certificate error is causing the message now, I would resolve that rather than change anything in the library

Best

-- 






Nithin Meppurathu

**Comment by subdesign** [comment]
chonthu: we had the same problem as nirradian, we just changed ssl certificates on the server. commenting out the exception line solved the error, pdf generates successfully, but please tell me what is the reason and how wkhtml2pdf is connected to ssl certificates, how can we resolve this error on server side? 
thanks

**Comment by chonthu** [comment]
Hey Barna,

If the server throws any warnings / errors in the response, the pdf generator will not show thinking the pdf might not show properly. What is the specific error in the response? Are you sure the ssl certificate is installed properly?

**Comment by subdesign** [comment]
Error message: 

```php
[2015-01-29 15:04:27] production.ERROR: exception 'Exception' with message 'System error <pre>Loading pages (1/6) [>                                                           ] 0
% [======>                                                     ] 10% [============>                                               ] 20% Warning: SSL error ignored                
                         [==================>                                         ] 30% [============================================================] 100% Counting pages (2/
6)                                                [============================================================] Object 1 of 1 Resolving links (4/6)                              
                          [============================================================] Object 1 of 1 Loading headers and footers (5/6)                                          
  Printing pages (6/6) [>                                                           ] Preparing [==============================>                             ] Page 1 of 2 [======
======================================================] Page 2 of 2 Done                                                                       </pre>' in /var/www/.svn/project/trunk/project/vendor/nitmedia/wkhtml2pdf/src/Nitmedia/Wkhtml2pdf/Wkhtml2pdf.php:883
```
running the binary on server generated a test pdf well. We don't understand again, how a command line tool connected to a ssl certificate?! Anyway the ssl seems to work, all sites run OK after the ssl cert. replaced with new one.

**Comment by chonthu** [comment]
When your running it on the command line are you using all the options that the plugin is using? Do you have https urls on the html your using to generate the pdf?


Best

-- 






Nithin Meppurathu

**Comment by subdesign** [comment]
yes, I have https , its running under a protected admin area. when we tested we run the binary with no options, only a website address and pdf filename as params.

**Comment by chonthu** [comment]
I would point all assets and urls within the pdf to a non ssl url, and serve the pdf on a secure url


Best

-- 






Nithin Meppurathu

**Comment by mikeredbike** [comment]
On the google cloud Debian had to run:
    sudo apt-get update
Then:
   sudo apt-get install libicu48

**Comment by dnlcesilva** [comment]
I have a similar error, can someone help me?

array(10) { [0]=> string(19) "Loading pages (1/6)" [1]=> string(159) "[> ] 0% [======> ] 10% Warning: SSL error ignored" [2]=> string(160) "[==========> ] 17% [=============> ] 22% Warning: SSL error ignored" [3]=> string(26) "Warning: SSL error ignored" [4]=> string(26) "Warning: SSL error ignored" [5]=> string(691) "[==================> ] 30% [======================> ] 37% [===========================> ] 46% [============================> ] 48% [=============================================> ] 75% [===============================================> ] 79% [=================================================> ] 82% [==================================================> ] 84% [====================================================> ] 88% [============================================================] 100% Counting pages (2/6)" [6]=> string(98) "[============================================================] Object 1 of 1 Resolving links (4/6)" [7]=> string(110) "[============================================================] Object 1 of 1 Loading headers and footers (5/6)" [8]=> string(20) "Printing pages (6/6)" [9]=> string(227) "[> ] Preparing [==============================> ] Page 1 of 2 [============================================================] Page 2 of 2 Done" }
