### ISSUE TITLE
[InvalidArgumentException] Configuration not found.

### ISSUE THREAD

**Issue by sentinel555** [NitMedia/wkhtml2pdf#44]
Hi, I must be doing something wrong that is very basic here. I've got a working binary of wkhtml2pdf installing on Debian Wheezy 32-bit.

However, when I run:

php artisan config:publish Nitmedia/Wkhtml2pdf

I get:

[InvalidArgumentException]  
  Configuration not found. 

I know I'm meant to set the correct driver, but I'm unsure which file to edit ?

**Comment by chonthu** [comment]
Case sensitivity in the package name?



Best

-- 






Nithin Meppurathu

**Comment by sentinel555** [comment]
I knew it would be something blindingly simple !!!
