### ISSUE TITLE
Images not appearing on pdf

### ISSUE THREAD

**Issue by kennethjaysone** [NitMedia/wkhtml2pdf#47]
```
return PDF::html('receipt.show', $data); 
```

displays the pdf with the html contents and css but the images dont appear. This is on a laravel homestead environment.

It's just an image on a view file:

```
<img class="img-responsive" src="img/receipt/banner.jpg">
```

The image is in

```
public/img/receipt/banner.jpg
```

**Comment by chonthu** [comment]
Absolute urls



Best

-- 






Nithin Meppurathu

**Comment by kennethjaysone** [comment]
It works. Thank you
