### ISSUE TITLE
Laravel 5 compatibility

### ISSUE THREAD

**Issue by BadChoice** [NitMedia/wkhtml2pdf#49]
Is it possible to add L5 compatibility?
What should be changed?

**Comment by chonthu** [comment]
Not much, just custom config and view classes for L5.



Best

-- 






Nithin Meppurathu

**Comment by BadChoice** [comment]
Will you do this? or can I try create a pull request, even I never made a serviceProvider :P

**Comment by chonthu** [comment]
Just got to find some time.



Best

-- 






Nithin Meppurathu

**Comment by ravaboard** [comment]
Looking forward to the support of this.

**Comment by Evertt** [comment]
+1

**Comment by BadChoice** [comment]
Hey I really need this updated for laravel 5.1, if anyobody can point me on how to adapt it I'll do it myself

Thanks!

**Comment by chonthu** [comment]
Ok guys, try dev master, I added a new service provider just for L5, let me know how it goes and I can tag after a couple days of testing

**Comment by BadChoice** [comment]
Hi Thank you so much!
Just got this error:

Exception in Wkhtml2pdf.php line 319:
Path must be absolute ("/usr/bin/wkhtmltopdf")

**Comment by chonthu** [comment]
Yes you need to have wkhtmltopdf installed and set to the right path in config. 



Best

-- 






Nithin Meppurathu

**Comment by BadChoice** [comment]
Ok.. and how to do it? isn't it installed with composer?

**Comment by chonthu** [comment]
Yes, I have some versions included right in the composer repo, to use that you have to publish the config. It used to be :

php artisan config:publish Nitmedia/Wkhtml2pdf

Let me know how it goes. Haven’t tried it in L5.



Best

-- 






Nithin Meppurathu

**Comment by chonthu** [comment]
@BadChoice Any luck?

**Comment by BadChoice** [comment]
I had to go yesterday, I'll try it again latter today
thank you so much!

**Comment by azidoner** [comment]
Got the same error message as @BadChoice. Not sure if I'm missing something but it doesn't seem to be reading from the config.php file. Got it working by manually changing binpath and binname variables in the main Wkhtml2pdf class.

**Comment by chonthu** [comment]
Thanks guys, I'll work on a fix



Best

-- 






Nithin Meppurathu

**Comment by avalore** [comment]
+1 for this. Any news?

**Comment by MyMediaMagnet** [comment]
I was able to get this working by editing a few core files.  Looking in the packages Laravel 5 service provider, I saw that it was in fact looking for a config file.  Then, in the packages Wkhtml2pdf.php, I noticed that it was looking for the config file Wkhtml2pdf.php.  I created this file in my /config folder, and added the contents of config.php from the package.  This still didn't work.  Looking closer at the packages Wkhtml2pdf.php file, I saw it was referencing these config settings by going $config->get('Wkhtml2pdf::binfile").  This doesn't work in Laravel 5, so it must be changed to $config->get('Wkhtml2pdf.binfile").  Once I made this change, the package started working for me.

By changing the php artisan config:publish command to a php artisan vendor:publish command, and by making these changes to the Wkhtml2pdf.php file, it should fix the package for Laravel 5.

**Comment by chonthu** [comment]
pull request @MyMediaMagnet ?

**Comment by drakakisgeo** [comment]
Followed @MyMediaMagnet instructions and I am also fine now.

**Comment by chonthu** [comment]
Marking resolved, closing ticket
