### ISSUE TITLE
pdf createing error in https mode

### ISSUE THREAD

**Issue by phil3209** [NitMedia/wkhtml2pdf#56]
I am using the wkhtml2pdf in laravel 5. And my project is using https mode.
In using "return PDF::html($bladename, $parasArray);" I got the following messages:
Exception in Wkhtml2pdf.php line 885: System error <pre>Loading pages (1/6)
[> ] 0%
[======> ] 10%
[========> ] 14%
[=========> ] 16%
[============> ] 20%
[==============> ] 24%
[===============> ] 26%
[=================> ] 29%
[=====================> ] 36%
Warning: Failed to load https://hr.seillc.com/css/globalForm.css (ignore)
[============================================================] 100%
Counting pages (2/6)
[============================================================] Object 1 of 1
Resolving links (4/6)
[============================================================] Object 1 of 1
Loading headers and footers (5/6)
Printing pages (6/6)
[> ] Preparing
[==============================> ] Page 1 of 2
[============================================================] Page 2 of 2
Done
Exit with code 1 due to network error: UnknownNetworkError
</pre>

I tested the "wget https://hr.seillc.com/css/globalForm.css" could work correctly without any warning.
And also in the apache access_log we could see that :  

10.68.198.58 - - [28/Oct/2016:03:48:11 -0500] "GET /js/jquery.js HTTP/1.1" 200 97244 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.34 (KHTML, like Gecko) wkhtmltopdf Safari/534.34"
10.68.198.58 - - [28/Oct/2016:03:48:11 -0500] "GET /css/jquery-ui.min.css HTTP/1.1" 200 19091 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.34 (KHTML, like Gecko) wkhtmltopdf Safari/534.34"
10.68.198.58 - - [28/Oct/2016:03:48:11 -0500] "GET /js/jquery-ui.min.js HTTP/1.1" 200 36675 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.34 (KHTML, like Gecko) wkhtmltopdf Safari/534.34"
10.68.198.58 - - [28/Oct/2016:03:48:11 -0500] "GET /js/global.js HTTP/1.1" 200 257 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.34 (KHTML, like Gecko) wkhtmltopdf Safari/534.34"
10.68.198.58 - - [28/Oct/2016:03:48:11 -0500] "GET /js/form.js HTTP/1.1" 200 7352 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.34 (KHTML, like Gecko) wkhtmltopdf Safari/534.34"
10.68.198.58 - - [28/Oct/2016:03:48:11 -0500] "GET /css/global.css HTTP/1.1" 200 3240 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.34 (KHTML, like Gecko) wkhtmltopdf Safari/534.34"

Some other js or css files could be loaded correctly, but when it came to globalForm.css the error happened　ｅｖｅｎ　ｉｆ　Ｉ　ｅｍｐｔｙ　ｔｈｅ　ｃｓｓ　ｆｉｌｅ＇ｓ　ｃｏｎｔｅｎｔ．

Ｃａｎ　ａｎｙｏｎｅ　ｈｅｌｐ　ｍｅ？　Ｔｈｘ．

**Comment by chonthu** [comment]
wkhtml2pdf doesnt work with https, this is a limitation not of this wrapper package.

**Comment by phil3209** [comment]
Thx. what a pity it can not work with https....

**Comment by chonthu** [comment]
Why does it need too? You can run it behind the scene on your server and generate the output via https
