### ISSUE TITLE
No class PDF exists after installation

### ISSUE THREAD

**Issue by jegjessing** [NitMedia/wkhtml2pdf#66]
In the usage you do a PDF::....
But there are no PDF class and Wkhtml2pdf not not have the methods as static members, so the usage example is not working for me :-1:

**Comment by chonthu** [comment]
You have to add 

'PDF'    => Nitmedia\Wkhtml2pdf\Facades\Wkhtml2pdf::class 

to aliases array, see L4 instructions

**Comment by jegjessing** [comment]
Ok, thanks. But a bit strange since I'm running L5.



Jarl Gjessing
CEO
StreamComposer
p:	+45 93 91 22 19  m: +45 60 72 17 16
a:	Klintevej 7, DK-3600 Frederikssund
w:	www.streamcomposer.com  e: jarlgjessing@gmail.com

**Comment by chonthu** [comment]
Yes it apply's to both.
