### ISSUE TITLE
Image from third party like google static map?

### ISSUE THREAD

**Issue by nguyenhaiphan** [NitMedia/wkhtml2pdf#67]
Is there any approach for image came from third party like like Google Static Map? I'm intend to use the url method , but can it support the session variables (so only admin roles can access to it, but from Pdf::url() ) ?

**Comment by chonthu** [comment]
Are you having a specific error with embedding external urls?

**Comment by nguyenhaiphan** [comment]
I'm sorry, please forget about this.
